services:
  # SERVIÇO 1: O Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: spring-store-db
    environment:
      - POSTGRES_DB=springstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # SERVIÇO 2: A Aplicação Spring Boot
  app:
    build: .
    container_name: spring-store-api
    ports:
      - "8080:8080"
    environment:
      # 1. Perfil do Banco
      - SPRING_PROFILES_ACTIVE=pg
      
      # 2. A PONTE DE SEGURANÇA
      # O Docker pega o valor do arquivo .env e passa para o container
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      
    depends_on:
      - db

volumes:
  postgres-data: